version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/django_backend:/code  # Ensure this path matches the structure and where your Django code resides
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=mongodb
      - DB_NAME=your-database-name
      - DB_USER=mongo_user
      - DB_PASS=mongo_pass
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "4201:4200"

volumes:
  mongodb-data:
